/* automatically generated by rust-bindgen 0.69.5 */
#![allow(non_upper_case_globals)]


pub const ML_DSA_44_PUBLICKEYBYTES: u32 = 1312;
pub const ML_DSA_44_SECRETKEYBYTES: u32 = 2560;
pub const ML_DSA_44_SIGBYTES: u32 = 2420;

pub const ML_DSA_65_PUBLICKEYBYTES: u32 = 1952;
pub const ML_DSA_65_SECRETKEYBYTES: u32 = 4032;
pub const ML_DSA_65_SIGBYTES: u32 = 3309;

pub const ML_DSA_87_PUBLICKEYBYTES: u32 = 2592;
pub const ML_DSA_87_SECRETKEYBYTES: u32 = 4896;
pub const ML_DSA_87_SIGBYTES: u32 = 4627;


pub const SLH_DSA_SHA2_128f_PUBLICKEYBYTES: u32 = 32;
pub const SLH_DSA_SHA2_128f_SECRETKEYBYTES: u32 = 64;
pub const SLH_DSA_SHA2_128f_SIGBYTES: u32 = 17088;

pub const SLH_DSA_SHA2_128s_PUBLICKEYBYTES: u32 = 32;
pub const SLH_DSA_SHA2_128s_SECRETKEYBYTES: u32 = 64;
pub const SLH_DSA_SHA2_128s_SIGBYTES: u32 = 7856;

pub const SLH_DSA_SHA2_192f_PUBLICKEYBYTES: u32 = 48;
pub const SLH_DSA_SHA2_192f_SECRETKEYBYTES: u32 = 96;
pub const SLH_DSA_SHA2_192f_SIGBYTES: u32 = 35664;

pub const SLH_DSA_SHA2_192s_PUBLICKEYBYTES: u32 = 48;
pub const SLH_DSA_SHA2_192s_SECRETKEYBYTES: u32 = 96;
pub const SLH_DSA_SHA2_192s_SIGBYTES: u32 = 16224;

pub const SLH_DSA_SHA2_256f_PUBLICKEYBYTES: u32 = 64;
pub const SLH_DSA_SHA2_256f_SECRETKEYBYTES: u32 = 128;
pub const SLH_DSA_SHA2_256f_SIGBYTES: u32 = 49856;

pub const SLH_DSA_SHA2_256s_PUBLICKEYBYTES: u32 = 64;
pub const SLH_DSA_SHA2_256s_SECRETKEYBYTES: u32 = 128;
pub const SLH_DSA_SHA2_256s_SIGBYTES: u32 = 29792;

pub const SLH_DSA_SHAKE_128f_PUBLICKEYBYTES: u32 = 32;
pub const SLH_DSA_SHAKE_128f_SECRETKEYBYTES: u32 = 64;
pub const SLH_DSA_SHAKE_128f_SIGBYTES: u32 = 17088;

pub const SLH_DSA_SHAKE_128s_PUBLICKEYBYTES: u32 = 32;
pub const SLH_DSA_SHAKE_128s_SECRETKEYBYTES: u32 = 64;
pub const SLH_DSA_SHAKE_128s_SIGBYTES: u32 = 7856;

pub const SLH_DSA_SHAKE_192f_PUBLICKEYBYTES: u32 = 48;
pub const SLH_DSA_SHAKE_192f_SECRETKEYBYTES: u32 = 96;
pub const SLH_DSA_SHAKE_192f_SIGBYTES: u32 = 35664;

pub const SLH_DSA_SHAKE_192s_PUBLICKEYBYTES: u32 = 48;
pub const SLH_DSA_SHAKE_192s_SECRETKEYBYTES: u32 = 96;
pub const SLH_DSA_SHAKE_192s_SIGBYTES: u32 = 16224;

pub const SLH_DSA_SHAKE_256f_PUBLICKEYBYTES: u32 = 64;
pub const SLH_DSA_SHAKE_256f_SECRETKEYBYTES: u32 = 128;
pub const SLH_DSA_SHAKE_256f_SIGBYTES: u32 = 49856;

pub const SLH_DSA_SHAKE_256s_PUBLICKEYBYTES: u32 = 64;
pub const SLH_DSA_SHAKE_256s_SECRETKEYBYTES: u32 = 128;
pub const SLH_DSA_SHAKE_256s_SIGBYTES: u32 = 29792;

pub const SLH_DSA_SM3_128f_PUBLICKEYBYTES: u32 = 32;
pub const SLH_DSA_SM3_128f_SECRETKEYBYTES: u32 = 64;
pub const SLH_DSA_SM3_128f_SIGBYTES: u32 = 17088;

pub const SLH_DSA_SM3_128s_PUBLICKEYBYTES: u32 = 32;
pub const SLH_DSA_SM3_128s_SECRETKEYBYTES: u32 = 64;
pub const SLH_DSA_SM3_128s_SIGBYTES: u32 = 7856;


pub const AIGIS_SIG1_PUBLICKEYBYTES: u32 = 1056;
pub const AIGIS_SIG1_SECRETKEYBYTES: u32 = 2448;
pub const AIGIS_SIG1_SIGBYTES: u32 = 1852;

pub const AIGIS_SIG2_PUBLICKEYBYTES: u32 = 1312;
pub const AIGIS_SIG2_SECRETKEYBYTES: u32 = 3376;
pub const AIGIS_SIG2_SIGBYTES: u32 = 2445;

pub const AIGIS_SIG3_PUBLICKEYBYTES: u32 = 1568;
pub const AIGIS_SIG3_SECRETKEYBYTES: u32 = 3888;
pub const AIGIS_SIG3_SIGBYTES: u32 = 3046;


pub const DILITHIUM2_PUBLICKEYBYTES: u32 = 1312;
pub const DILITHIUM2_SECRETKEYBYTES: u32 = 2528;
pub const DILITHIUM2_SIGBYTES: u32 = 2420;

pub const DILITHIUM3_PUBLICKEYBYTES: u32 = 1952;
pub const DILITHIUM3_SECRETKEYBYTES: u32 = 4000;
pub const DILITHIUM3_SIGBYTES: u32 = 3293;

pub const DILITHIUM5_PUBLICKEYBYTES: u32 = 2592;
pub const DILITHIUM5_SECRETKEYBYTES: u32 = 4864;
pub const DILITHIUM5_SIGBYTES: u32 = 4595;


pub const SPHINCS_A_SHA2_128f_PUBLICKEYBYTES: u32 = 32;
pub const SPHINCS_A_SHA2_128f_SECRETKEYBYTES: u32 = 64;
pub const SPHINCS_A_SHA2_128f_SIGBYTES: u32 = 16720;

pub const SPHINCS_A_SHA2_128s_PUBLICKEYBYTES: u32 = 32;
pub const SPHINCS_A_SHA2_128s_SECRETKEYBYTES: u32 = 64;
pub const SPHINCS_A_SHA2_128s_SIGBYTES: u32 = 6880;

pub const SPHINCS_A_SHA2_192f_PUBLICKEYBYTES: u32 = 48;
pub const SPHINCS_A_SHA2_192f_SECRETKEYBYTES: u32 = 96;
pub const SPHINCS_A_SHA2_192f_SIGBYTES: u32 = 34896;

pub const SPHINCS_A_SHA2_192s_PUBLICKEYBYTES: u32 = 48;
pub const SPHINCS_A_SHA2_192s_SECRETKEYBYTES: u32 = 96;
pub const SPHINCS_A_SHA2_192s_SIGBYTES: u32 = 14568;

pub const SPHINCS_A_SHA2_256f_PUBLICKEYBYTES: u32 = 64;
pub const SPHINCS_A_SHA2_256f_SECRETKEYBYTES: u32 = 128;
pub const SPHINCS_A_SHA2_256f_SIGBYTES: u32 = 49312;

pub const SPHINCS_A_SHA2_256s_PUBLICKEYBYTES: u32 = 64;
pub const SPHINCS_A_SHA2_256s_SECRETKEYBYTES: u32 = 128;
pub const SPHINCS_A_SHA2_256s_SIGBYTES: u32 = 27232;

pub const SPHINCS_A_SHAKE_128f_PUBLICKEYBYTES: u32 = 32;
pub const SPHINCS_A_SHAKE_128f_SECRETKEYBYTES: u32 = 64;
pub const SPHINCS_A_SHAKE_128f_SIGBYTES: u32 = 16720;

pub const SPHINCS_A_SHAKE_128s_PUBLICKEYBYTES: u32 = 32;
pub const SPHINCS_A_SHAKE_128s_SECRETKEYBYTES: u32 = 64;
pub const SPHINCS_A_SHAKE_128s_SIGBYTES: u32 = 6880;

pub const SPHINCS_A_SHAKE_192f_PUBLICKEYBYTES: u32 = 48;
pub const SPHINCS_A_SHAKE_192f_SECRETKEYBYTES: u32 = 96;
pub const SPHINCS_A_SHAKE_192f_SIGBYTES: u32 = 34896;

pub const SPHINCS_A_SHAKE_192s_PUBLICKEYBYTES: u32 = 48;
pub const SPHINCS_A_SHAKE_192s_SECRETKEYBYTES: u32 = 96;
pub const SPHINCS_A_SHAKE_192s_SIGBYTES: u32 = 14568;

pub const SPHINCS_A_SHAKE_256f_PUBLICKEYBYTES: u32 = 64;
pub const SPHINCS_A_SHAKE_256f_SECRETKEYBYTES: u32 = 128;
pub const SPHINCS_A_SHAKE_256f_SIGBYTES: u32 = 49312;

pub const SPHINCS_A_SHAKE_256s_PUBLICKEYBYTES: u32 = 64;
pub const SPHINCS_A_SHAKE_256s_SECRETKEYBYTES: u32 = 128;
pub const SPHINCS_A_SHAKE_256s_SIGBYTES: u32 = 27232;

pub const SPHINCS_A_SM3_128f_PUBLICKEYBYTES: u32 = 32;
pub const SPHINCS_A_SM3_128f_SECRETKEYBYTES: u32 = 64;
pub const SPHINCS_A_SM3_128f_SIGBYTES: u32 = 16720;

pub const SPHINCS_A_SM3_128s_PUBLICKEYBYTES: u32 = 32;
pub const SPHINCS_A_SM3_128s_SECRETKEYBYTES: u32 = 64;
pub const SPHINCS_A_SM3_128s_SIGBYTES: u32 = 6880;





pub const ML_KEM_512_PUBLICKEYBYTES: u32 = 800;
pub const ML_KEM_512_SECRETKEYBYTES: u32 = 1632;
pub const ML_KEM_512_CIPHERTEXTBYTES: u32 = 768;
pub const ML_KEM_512_SSBYTES: u32 = 32;

pub const ML_KEM_768_PUBLICKEYBYTES: u32 = 1184;
pub const ML_KEM_768_SECRETKEYBYTES: u32 = 2400;
pub const ML_KEM_768_CIPHERTEXTBYTES: u32 = 1088;
pub const ML_KEM_768_SSBYTES: u32 = 32;

pub const ML_KEM_1024_PUBLICKEYBYTES: u32 = 1568;
pub const ML_KEM_1024_SECRETKEYBYTES: u32 = 3168;
pub const ML_KEM_1024_CIPHERTEXTBYTES: u32 = 1568;
pub const ML_KEM_1024_SSBYTES: u32 = 32;


pub const KYBER512_PUBLICKEYBYTES: u32 = 800;
pub const KYBER512_SECRETKEYBYTES: u32 = 1632;
pub const KYBER512_CIPHERTEXTBYTES: u32 = 768;
pub const KYBER512_SSBYTES: u32 = 32;

pub const KYBER768_PUBLICKEYBYTES: u32 = 1184;
pub const KYBER768_SECRETKEYBYTES: u32 = 2400;
pub const KYBER768_CIPHERTEXTBYTES: u32 = 1088;
pub const KYBER768_SSBYTES: u32 = 32;

pub const KYBER1024_PUBLICKEYBYTES: u32 = 1568;
pub const KYBER1024_SECRETKEYBYTES: u32 = 3168;
pub const KYBER1024_CIPHERTEXTBYTES: u32 = 1568;
pub const KYBER1024_SSBYTES: u32 = 32;


pub const AIGIS_ENC_1_PUBLICKEYBYTES: u32 = 672;
pub const AIGIS_ENC_1_SECRETKEYBYTES: u32 = 1568;
pub const AIGIS_ENC_1_CIPHERTEXTBYTES: u32 = 736;
pub const AIGIS_ENC_1_SSBYTES: u32 = 32;

pub const AIGIS_ENC_2_PUBLICKEYBYTES: u32 = 896;
pub const AIGIS_ENC_2_SECRETKEYBYTES: u32 = 2208;
pub const AIGIS_ENC_2_CIPHERTEXTBYTES: u32 = 992;
pub const AIGIS_ENC_2_SSBYTES: u32 = 32;

pub const AIGIS_ENC_3_PUBLICKEYBYTES: u32 = 992;
pub const AIGIS_ENC_3_SECRETKEYBYTES: u32 = 2304;
pub const AIGIS_ENC_3_CIPHERTEXTBYTES: u32 = 1056;
pub const AIGIS_ENC_3_SSBYTES: u32 = 32;

pub const AIGIS_ENC_4_PUBLICKEYBYTES: u32 = 1440;
pub const AIGIS_ENC_4_SECRETKEYBYTES: u32 = 3168;
pub const AIGIS_ENC_4_CIPHERTEXTBYTES: u32 = 1568;
pub const AIGIS_ENC_4_SSBYTES: u32 = 32;


unsafe extern "C" {
    pub fn pqmagic_ml_dsa_44_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_44_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_44_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_44_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_44_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_65_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_65_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_65_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_65_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_65_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_87_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_87_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_87_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_87_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_dsa_87_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_128s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_192s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sha2_256s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_128s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_192s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_shake_256s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_slh_dsa_sm3_128s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig1_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig1_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig1_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig1_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig1_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig2_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig2_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig2_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig2_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig2_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig3_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig3_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig3_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig3_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_sig3_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        ctx: *const ::std::os::raw::c_uchar,
        ctx_len: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium2_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium2_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium2_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium2_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium2_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium3_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium3_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium3_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium3_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium3_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium5_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium5_std_signature(
        sig: *mut ::std::os::raw::c_uchar,
        siglen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium5_std_verify(
        sig: *const ::std::os::raw::c_uchar,
        siglen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium5_std(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_dilithium5_std_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_128s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_192s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sha2_256s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_128s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_192s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_shake_256s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128f_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128f_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128f_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128f_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128f_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128s_simple_std_sign_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128s_simple_std_sign_signature(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128s_simple_std_sign_verify(
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128s_simple_std_sign(
        sm: *mut ::std::os::raw::c_uchar,
        smlen: *mut usize,
        m: *const ::std::os::raw::c_uchar,
        mlen: usize,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_sphincs_a_sm3_128s_simple_std_sign_open(
        m: *mut ::std::os::raw::c_uchar,
        mlen: *mut usize,
        sm: *const ::std::os::raw::c_uchar,
        smlen: usize,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_512_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_512_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_512_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_768_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_768_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_768_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_1024_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_1024_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_ml_kem_1024_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber512_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber512_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber512_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber768_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber768_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber768_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber1024_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber1024_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_kyber1024_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_1_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_1_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_1_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_2_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_2_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_2_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_3_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_3_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_3_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_4_std_keypair(
        pk: *mut ::std::os::raw::c_uchar,
        sk: *mut ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_4_std_enc(
        ct: *mut ::std::os::raw::c_uchar,
        ss: *mut ::std::os::raw::c_uchar,
        pk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pqmagic_aigis_enc_4_std_dec(
        ss: *mut ::std::os::raw::c_uchar,
        ct: *const ::std::os::raw::c_uchar,
        sk: *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_int;
}
